# Generated by Django 5.0.4 on 2024-04-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/%Y/%M/%D')),
                ('text', models.TextField()),
                ('date_publish', models.DateTimeField()),
                ('update', models.DateTimeField()),
                ('status', models.CharField(choices=[('d', 'draft'), ('p', 'publish')], max_length=1)),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-update'],
            },
        ),
    ]
