# Generated by Django 5.0.4 on 2024-04-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=models.TextField(default=1, verbose_name='text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text_fa',
            field=models.TextField(default=1, verbose_name='text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(default=1, max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title_fa',
            field=models.CharField(default=1, max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
    ]
